### ISSUE TITLE
System.InvalidOperationException: A sequência não contém elementos (BDHero GUI v0.9.0.3)

### ISSUE THREAD

**Issue by bdhero-issues** [bdhero/bdhero#16]
BDHero GUI v0.9.0.3 portable (built on 2014-04-02 03:45:00Z)
## Stack Trace

```
System.InvalidOperationException: A sequência não contém elementos
   em System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   em BDHero.Plugin.AutoDetector.AutoDetector.SelectBestTracks(Disc disc)
   em BDHero.Plugin.AutoDetector.AutoDetector.AutoDetect(CancellationToken cancellationToken, Job job)
   em BDHero.Controller.<>c__DisplayClass35.<AutoDetect>b__34(CancellationToken token)
   em BDHero.Controller.<>c__DisplayClass24.<RunPluginSync>b__22(IPromise`1 param0)
   em DotNetUtils.Concurrency.Promise`1.Work()
   em DotNetUtils.Concurrency.Promise`1.TryDoWork()
```
## Plugins

| R/O | Plugin Name | Version | Build Date | E/D |
| --- | --- | --- | --- | --- |
| 0 | BDInfo Disc Reader | 0.5.8.2 | 2014-04-02 03:44:52Z |  |
| 0 | ISAN Metadata Provider | 0.9.0.3 | 2014-04-02 03:44:53Z |  |
| 1 | TMDb | 0.9.0.3 | 2014-04-02 03:44:52Z |  |
| 2 | ChapterDb | 0.9.0.3 | 2014-04-02 03:44:51Z |  |
| 0 | BDHero Detective | 0.9.0.3 | 2014-04-02 03:44:52Z |  |
| 0 | BDHero File Namer | 0.9.0.3 | 2014-04-02 03:44:52Z |  |
| 0 | FFmpeg | 2.1.0.1 | 2014-04-02 03:44:56Z |  |
## System Info

```
OS: 
    Type: Windows
    VersionNumber: 6.1.7601.65536
    VersionString: Microsoft Windows NT 6.1.7601 Service Pack 1
    Is64Bit: True
Hardware: 
    ProcessorCount: 12
    TotalPhysicalMemory: 12875583488 bytes (12,0 GiB)
    AvailableMemory: 10520891392 bytes (9,8 GiB)
Process: 
    MemoryWidth: 64
    Is64Bit: True
```

**Comment by bdhero-issues** [comment]
BDHero GUI v0.9.0.3 portable (built on 2014-04-02 03:45:00Z)

## Stack Trace

```
System.InvalidOperationException: A sequência não contém elementos
   em System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   em BDHero.Plugin.AutoDetector.AutoDetector.SelectBestTracks(Disc disc)
   em BDHero.Plugin.AutoDetector.AutoDetector.AutoDetect(CancellationToken cancellationToken, Job job)
   em BDHero.Controller.<>c__DisplayClass35.<AutoDetect>b__34(CancellationToken token)
   em BDHero.Controller.<>c__DisplayClass24.<RunPluginSync>b__22(IPromise`1 param0)
   em DotNetUtils.Concurrency.Promise`1.Work()
   em DotNetUtils.Concurrency.Promise`1.TryDoWork()
```

## Plugins

| R/O | Plugin Name | Version | Build Date | E/D |
| --- | --- | --- | --- | --- |
| 0 | BDInfo Disc Reader | 0.5.8.2 | 2014-04-02 03:44:52Z |  |
| 0 | ISAN Metadata Provider | 0.9.0.3 | 2014-04-02 03:44:53Z |  |
| 1 | TMDb | 0.9.0.3 | 2014-04-02 03:44:52Z |  |
| 2 | ChapterDb | 0.9.0.3 | 2014-04-02 03:44:51Z |  |
| 0 | BDHero Detective | 0.9.0.3 | 2014-04-02 03:44:52Z |  |
| 0 | BDHero File Namer | 0.9.0.3 | 2014-04-02 03:44:52Z |  |
| 0 | FFmpeg | 2.1.0.1 | 2014-04-02 03:44:56Z |  |

## System Info

```
OS: 
    Type: Windows
    VersionNumber: 6.1.7601.65536
    VersionString: Microsoft Windows NT 6.1.7601 Service Pack 1
    Is64Bit: True
Hardware: 
    ProcessorCount: 12
    TotalPhysicalMemory: 12875583488 bytes (12,0 GiB)
    AvailableMemory: 10517483520 bytes (9,8 GiB)
Process: 
    MemoryWidth: 64
    Is64Bit: True
```
