### ISSUE TITLE
System.NullReferenceException: Riferimento a un oggetto non impostato su un'istanza di oggetto. (BDHero GUI v0.9.0.3)

### ISSUE THREAD

**Issue by bdhero-issues** [bdhero/bdhero#17]
BDHero GUI v0.9.0.3 portable (built on 2014-04-02 08:45:00Z)
## Stack Trace

```
System.NullReferenceException: Riferimento a un oggetto non impostato su un'istanza di oggetto.
   in BDHero.Plugin.DiscReader.Transformer.DiscFileSystemTransformer.GetJacketImage(JacketSize jacketSize, DirectoryInfo dir)
   in BDHero.Plugin.DiscReader.Transformer.DiscFileSystemTransformer.Transform(BDROM bdrom, Disc disc)
   in BDHero.Plugin.DiscReader.Transformer.DiscTransformer.Transform(BDROM bdrom)
   in BDHero.Plugin.DiscReader.DiscReader.ReadBDROM(CancellationToken cancellationToken, String bdromPath)
   in BDHero.Controller.<>c__DisplayClass29.<ReadBDROM>b__27(CancellationToken token)
   in BDHero.Controller.<>c__DisplayClass24.<RunPluginSync>b__22(IPromise`1 param0)
   in DotNetUtils.Concurrency.Promise`1.Work()
   in DotNetUtils.Concurrency.Promise`1.TryDoWork()
```
## Plugins

| R/O | Plugin Name | Version | Build Date | E/D |
| --- | --- | --- | --- | --- |
| 0 | BDInfo Disc Reader | 0.5.8.2 | 2014-04-02 08:44:52Z |  |
| 0 | ISAN Metadata Provider | 0.9.0.3 | 2014-04-02 08:44:53Z |  |
| 1 | TMDb | 0.9.0.3 | 2014-04-02 08:44:52Z |  |
| 2 | ChapterDb | 0.9.0.3 | 2014-04-02 08:44:51Z |  |
| 0 | BDHero Detective | 0.9.0.3 | 2014-04-02 08:44:52Z |  |
| 0 | BDHero File Namer | 0.9.0.3 | 2014-04-02 08:44:52Z |  |
| 0 | FFmpeg | 2.1.0.1 | 2014-04-02 08:44:56Z |  |
## System Info

```
OS: 
    Type: Windows
    VersionNumber: 6.1.7601.65536
    VersionString: Microsoft Windows NT 6.1.7601 Service Pack 1
    Is64Bit: True
Hardware: 
    ProcessorCount: 4
    TotalPhysicalMemory: 4177547264 bytes (3,9 GiB)
    AvailableMemory: 1588625408 bytes (1,5 GiB)
Process: 
    MemoryWidth: 64
    Is64Bit: True
```

**Comment by bdhero-issues** [comment]
BDHero GUI v0.9.0.3 portable (built on 2014-04-02 08:45:00Z)

## Stack Trace

```
System.NullReferenceException: Riferimento a un oggetto non impostato su un'istanza di oggetto.
   in BDHero.Plugin.DiscReader.Transformer.DiscFileSystemTransformer.GetJacketImage(JacketSize jacketSize, DirectoryInfo dir)
   in BDHero.Plugin.DiscReader.Transformer.DiscFileSystemTransformer.Transform(BDROM bdrom, Disc disc)
   in BDHero.Plugin.DiscReader.Transformer.DiscTransformer.Transform(BDROM bdrom)
   in BDHero.Plugin.DiscReader.DiscReader.ReadBDROM(CancellationToken cancellationToken, String bdromPath)
   in BDHero.Controller.<>c__DisplayClass29.<ReadBDROM>b__27(CancellationToken token)
   in BDHero.Controller.<>c__DisplayClass24.<RunPluginSync>b__22(IPromise`1 param0)
   in DotNetUtils.Concurrency.Promise`1.Work()
   in DotNetUtils.Concurrency.Promise`1.TryDoWork()
```

## Plugins

| R/O | Plugin Name | Version | Build Date | E/D |
| --- | --- | --- | --- | --- |
| 0 | BDInfo Disc Reader | 0.5.8.2 | 2014-04-02 08:44:52Z |  |
| 0 | ISAN Metadata Provider | 0.9.0.3 | 2014-04-02 08:44:53Z |  |
| 1 | TMDb | 0.9.0.3 | 2014-04-02 08:44:52Z |  |
| 2 | ChapterDb | 0.9.0.3 | 2014-04-02 08:44:51Z |  |
| 0 | BDHero Detective | 0.9.0.3 | 2014-04-02 08:44:52Z |  |
| 0 | BDHero File Namer | 0.9.0.3 | 2014-04-02 08:44:52Z |  |
| 0 | FFmpeg | 2.1.0.1 | 2014-04-02 08:44:56Z |  |

## System Info

```
OS: 
    Type: Windows
    VersionNumber: 6.1.7601.65536
    VersionString: Microsoft Windows NT 6.1.7601 Service Pack 1
    Is64Bit: True
Hardware: 
    ProcessorCount: 8
    TotalPhysicalMemory: 33245237248 bytes (31,0 GiB)
    AvailableMemory: 27728756736 bytes (25,8 GiB)
Process: 
    MemoryWidth: 64
    Is64Bit: True
```
