### ISSUE TITLE
System.FormatException: Входная строка имела неверный формат. (BDHero GUI v0.9.0.4)

### ISSUE THREAD

**Issue by bdhero-issues** [bdhero/bdhero#19]
BDHero GUI v0.9.0.4 (built on 2014-04-03 08:02:55Z)
## Stack Trace

```
System.FormatException: Входная строка имела неверный формат.
   в BDHero.Plugin.FFmpegMuxer.FFmpegPlugin.Mux(CancellationToken cancellationToken, Job job)
   в BDHero.Controller.<>c__DisplayClass42.<Mux>b__41(CancellationToken token)
   в BDHero.Controller.<>c__DisplayClass24.<RunPluginSync>b__22(IPromise`1 param0)
   в DotNetUtils.Concurrency.Promise`1.Work()
   в DotNetUtils.Concurrency.Promise`1.TryDoWork()
```
## Plugins

| R/O | Plugin Name | Version | Build Date | E/D |
| --- | --- | --- | --- | --- |
| 0 | BDInfo Disc Reader | 0.5.8.2 | 2014-04-03 08:02:49Z |  |
| 0 | ISAN Metadata Provider | 0.9.0.4 | 2014-04-03 08:02:51Z |  |
| 1 | TMDb | 0.9.0.4 | 2014-04-03 08:02:49Z |  |
| 2 | ChapterDb | 0.9.0.4 | 2014-04-03 08:02:48Z |  |
| 0 | BDHero Detective | 0.9.0.4 | 2014-04-03 08:02:49Z |  |
| 0 | BDHero File Namer | 0.9.0.4 | 2014-04-03 08:02:49Z |  |
| 0 | FFmpeg | 2.1.0.1 | 2014-04-03 08:02:52Z |  |
## System Info

```
OS: 
    Type: Windows
    VersionNumber: 6.3.9600.0
    VersionString: Microsoft Windows NT 6.3.9600.0
    Is64Bit: True
Hardware: 
    ProcessorCount: 4
    TotalPhysicalMemory: 4101263360 bytes (3,8 GiB)
    AvailableMemory: 1032245248 bytes (984,4 MiB)
Process: 
    MemoryWidth: 64
    Is64Bit: True
```
