### ISSUE TITLE
BDHero.Plugin.FFmpegMuxer.FFmpegException: FFmpeg exited with state: Error (BDHero GUI v0.9.0.4)

### ISSUE THREAD

**Issue by bdhero-issues** [bdhero/bdhero#20]
BDHero GUI v0.9.0.4 (built on 2014-04-03 06:02:55Z)
## Stack Trace

```
BDHero.Plugin.FFmpegMuxer.FFmpegException: FFmpeg exited with state: Error
   en BDHero.Plugin.FFmpegMuxer.FFmpegPlugin.Mux(CancellationToken cancellationToken, Job job)
   en BDHero.Controller.<>c__DisplayClass42.<Mux>b__41(CancellationToken token)
   en BDHero.Controller.<>c__DisplayClass24.<RunPluginSync>b__22(IPromise`1 param0)
   en DotNetUtils.Concurrency.Promise`1.Work()
   en DotNetUtils.Concurrency.Promise`1.TryDoWork()
```
## Plugins

| R/O | Plugin Name | Version | Build Date | E/D |
| --- | --- | --- | --- | --- |
| 0 | BDInfo Disc Reader | 0.5.8.2 | 2014-04-03 06:02:49Z |  |
| 0 | ISAN Metadata Provider | 0.9.0.4 | 2014-04-03 06:02:51Z |  |
| 1 | TMDb | 0.9.0.4 | 2014-04-03 06:02:49Z |  |
| 2 | ChapterDb | 0.9.0.4 | 2014-04-03 06:02:48Z |  |
| 0 | BDHero Detective | 0.9.0.4 | 2014-04-03 06:02:49Z |  |
| 0 | BDHero File Namer | 0.9.0.4 | 2014-04-03 06:02:49Z |  |
| 0 | FFmpeg | 2.1.0.1 | 2014-04-03 06:02:52Z |  |
## System Info

```
OS: 
    Type: Windows
    VersionNumber: 6.1.7601.65536
    VersionString: Microsoft Windows NT 6.1.7601 Service Pack 1
    Is64Bit: True
Hardware: 
    ProcessorCount: 8
    TotalPhysicalMemory: 8566747136 bytes (8,0 GiB)
    AvailableMemory: 1260109824 bytes (1,2 GiB)
Process: 
    MemoryWidth: 64
    Is64Bit: True
```
